### ISSUE TITLE
Build instructions suggest disabling erroneous feed locations. Why?

### ISSUE THREAD

**Issue by Hurricos** [libremesh/lime-web#140]
From https://libremesh.org/development.html:
> Optionally, deselect erroneous feeds locations:
> - Image configuration → Separate feed repositories → Enable feed libremesh
> - Image configuration → Separate feed repositories → Enable feed profiles

Why should one deselect the libremesh feed? Isn't that where the Libremesh default packages should be coming from?

If we should be enabling everything *except* the libremesh and 'profiles' feeds when building, I'd like to clarify the wording. The parent commit, 57df50b2, isn't clear why this is worded this way.

```diff
diff --git a/development.txt b/development.txt
index 1fefa26..4afbd2a 100644
--- a/development.txt
+++ b/development.txt
@@ -101,7 +101,7 @@ Check out the +target+ (e.g. +ATH79+), +subtarget+ (e.g. +generic+) and +profile
 Select the _Target System_, _Subtarget_ and _Target Profile_ accordingly.
 
 
-Optionally, **deselect** erroneous feeds locations:
+Optionally, **deselect** all feed locations except for the correct ones (this prevents upstream packages from taking priority):
 
 - Image configuration → Separate feed repositories → Enable feed libremesh
 - Image configuration → Separate feed repositories → Enable feed profiles
```

**Comment by ilario** [comment]
Those entries would cause the OPKG to look for a repository named "libremesh" and another named "profiles" on OpenWrt's servers.
The problem is that those repositories are not on OpenWrt servers (it would make sense to have them there, but that would require some effort that has never been done (there have been a few exceptions, for example @aparcar pushed a some packages there)) but on LibreMesh servers.
So, the entries for those repositories are beeing added here:
https://github.com/libremesh/lime-packages/blob/master/packages/lime-system/files/etc/uci-defaults/92_add-lime-repos
Did I get your point?

**Comment by Hurricos** [comment]
Oh! This is much different than I understood. So you are deselecting the default locations from `downloads.openwrt.org` that would be generated based on those new `libremesh` and `profiles` feeds.

That makes sense now, thank you. Would you mind linking this issue after "Optionally, deselect erroneous feeds locations:" in [the documentation](https://libremesh.org/development.html), so it's clearer for the next reader?

Cheers.
