### ISSUE TITLE
Add Spanish mailing list to site

### ISSUE THREAD

**Issue by nicopace** [libremesh/lime-web#24]
This is the link: https://lists.libremesh.org/mailman/listinfo/lime-es

**Comment by ilario** [comment]
[lime-users](https://lists.libremesh.org/mailman/listinfo/lime-users) has always been multilingual ([al least since its second email](https://lists.libremesh.org/pipermail/lime-users/2014-December/000001.html)), why do we need a spanish mailing list?

**Comment by nicopace** [comment]
@nicoechaniz can reply to this :)

**Comment by nicoechaniz** [comment]
this was proposed by a number of community networks administrators in Argentina who feel more at ease participating in a list where they can understand the conversations that take place rather than not understand the general discussion and then just be able to send their ask their questions in their own language.
The current list poorly represents the spanish speaking community that uses LibreMesh, which is a big portion of the users. So this is an attempt at nurturing that community.

**Comment by ilario** [comment]
that direction should be added in this page: http://libremesh.org/communication.html via PR to [this file](/libremesh/lime-web/blob/master/communication.txt)
